[tool.poetry]
name = "project-2"
version = "0.1.0"
description = ""
authors = ["'isheng' <110703011@g.nccu.edu.tw>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyserini = "^0.43.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
